spring.application.name=ingress-service

spring.docker.compose.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3307/ingress_db
spring.datasource.username=root
spring.datasource.password=verysecret
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=localhost:9092